# Generated by Django 6.0.6 on 2026-09-12

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=wagtail.fields.RichTextField(
                features=[
                    'h2',
                    'h3',
                    'bold',
                    'italic',
                    'ol',
                    'ul',
                    'link',
                    'document-link',
                    'image',
                    'embed',
                ],
                verbose_name='正文',
            ),
        ),
    ]
